# Generated by Django 6.0.6 on 2026-06-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('departemen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('gaji_pokok', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tunjangan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gaji', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggajian', to='karyawan.karyawan')),
            ],
        ),
    ]
